---
- hosts: all
  gather_facts: True
  tasks:
    - set_fact:
        testip:
          - "192.168.1.2"
          - "10.0.2.15"
    - name: test
      debug:
        msg: "{{ testip | ipaddr('10.0.2.0/24') }}"
